scripts/tasks/detect-vagrant.yml
=> Fix vagrant detection

scripts/provision.yml
https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning
=> Install packages to avoid insecure platform warnings

docs/README.md
=> Amendments to README.md

cikit, cmf/all/scripts/actions.yml, cmf/all/scripts/reinstall.yml, cmf/all/scripts/tasks/reinstall/actions.yml, docs/README.md, docs/jenkins/builds-actions/README.md, docs/jenkins/github-bot/README.md, docs/matrix/domain/README.md, scripts/roles/cikit-jenkins/templates/jobs/builder.xml.j2, scripts/roles/cikit-jenkins/templates/jobs/pr_builder.xml.j2, scripts/roles/cikit-jenkins/templates/jobs/server_cleaner.xml.j2
https://github.com/BR0kEN-/cikit/issues/32
=> [Jenkins] Handle actions from commit messages

scripts/roles/cikit-jenkins/tasks/install.yml, scripts/roles/cikit-jenkins/tasks/main.yml, scripts/roles/cikit-jenkins/templates/configs/jenkins.model.DownloadSettings.xml.j2
https://github.com/BR0kEN-/cikit/issues/35
=> [CIKit][Jenkins] Fix enabling of HTML markup formatter

cikit, cmf/all/.cikit/.vagrant/provisioners/cikit/provisioner.rb, cmf/all/.gitignore
https://github.com/BR0kEN-/cikit/issues/37
=> [CIKit] Allow to ship environment configuration

cikit, docs/basic-http-auth/README.md, scripts/provision.yml, scripts/roles/cikit-security/defaults/main.yml, scripts/tasks/password.yml, scripts/vars/security.yml
https://github.com/BR0kEN-/cikit/issues/39
=> Generate "http_auth_pass" if not set explicitly

.gitignore, .travis.yml, host/add.yml, host/tasks/host/append.yml, lib/inventory, tests/travis/inventory.sh
=> #91: Do not require ".hosts.json" to be presented

docs/_changelog/2018-01-16/README.md, docs/_changelog/2018-01-28/README.md, scripts/provision.yml, scripts/roles/cikit-ruby/tasks/main.yml, scripts/roles/cikit-ruby/vars/main.yml
https://github.com/BR0kEN-/cikit/issues/93
=> #93: Speed up Ruby installation

docs/_changelog/2018-01-30/README.md, scripts/provision.yml, scripts/roles/cikit-php/defaults/main.yml, scripts/roles/cikit-php/tasks/main.yml, scripts/roles/cikit-php/tasks/xdebug.yml, scripts/roles/cikit-php/vars/main.yml
https://github.com/BR0kEN-/cikit/issues/75
=> #75: Add support of PHP 7.2 and Xdebug 2.6

.travis.yml, cmf/drupal/main.yml, cmf/wordpress/main.yml, docs/_changelog/2018-03-04/README.md, docs/_data/navigation.yml, docs/_documentation/project/cmf-integration/README.md, scripts/init.yml, tests/travis/init.sh
https://github.com/BR0kEN-/cikit/issues/101
=> #101: Improve API for integrating new CMF/CMS

cmf/all/.gitignore, cmf/all/scripts/tasks/database/import-strategies/platformsh.yml, docs/_changelog/2018-03-10/README.md, docs/_data/navigation.yml, docs/_documentation/project/mysql-import-strategies/README.md, docs/_documentation/workflow/platformsh/README.md, scripts/provision.yml, scripts/roles/cikit-composer/tasks/main.yml, scripts/roles/cikit-mssql/tasks/main.yml, scripts/roles/cikit-platformsh-cli/tasks/main.yml, scripts/roles/cikit-platformsh-cli/vars/main.yml, scripts/roles/cikit-ruby/tasks/main.yml
=> #95: Add Platform.sh integration

scripts/roles/cikit-apache2/templates/vhosts.conf.j2
=> Fixes #112: Fix "Directory" Apache2 definition for local environment

docs/_documentation/workflow/platformsh/README.md, lib/platformsh/setup.sh, scripts/roles/cikit-platformsh-cli/tasks/main.yml, vagrant/Vagrantfile
=> #116: Automate Platform.sh integration

.travis.yml, env/tasks/create.yml, lib/__init__.py, lib/arguments.py, lib/functions.py, scripts/provision.yml, scripts/roles/cikit-solr/vars/main.yml, scripts/tasks/project-variable.yml, tests/cikit.sh, tests/lib/cikit.sh, tests/travis/provision.sh
=> #118: Run "cikit provision" in dockerized environment

cmf/all/scripts/tasks/bash.yml, cmf/drupal/all/scripts/tasks/drush.yml, cmf/drupal/all/scripts/tasks/reinstall/modes/full.yml, cmf/wordpress/4/scripts/tasks/reinstall/modes/full.yml, cmf/wordpress/4/scripts/tasks/wp.yml, cmf/wordpress/all/scripts/vars/environments/default.yml, cmf/wordpress/all/scripts/vars/environments/demo.yml, docs/_data/navigation.yml, docs/_documentation/project/reinstall/README.md
=> #126: Allow conditions for Bash, Drush and WP commands during "cikit reinstall"

lib/functions.py, lib/variables.py, tests/travis/python/__init__.py, tests/travis/python/is_version_between.py, tests/travis/python/parse_extra_vars.py, tests/travis/python/task_bash.py, tests/travis/python/task_drush.py
=> #128: Add unit tests for "cmf/all/scripts/tasks/bash.yml" and "cmf/drupal/all/scripts/tasks/drush.yml"

lib/variables.py, scripts/roles/cikit-jenkins/tasks/cli.yml
https://github.com/BR0kEN-/cikit/issues/141
=> #141: Add all paths to site packages when Python for Ansible is not a system-wide

scripts/roles/cikit-nginx/templates/cikit.j2, scripts/roles/cikit-nginx/templates/snippets/cors-preflight.conf.j2, scripts/roles/cikit-nginx/templates/snippets/site-locations.conf.j2
https://github.com/BR0kEN-/cikit/issues/145
=> #145: Allow Nginx to handle preflight (OPTIONS) requests

matrix/templates/nginx/vhosts/droplets.j2
https://github.com/BR0kEN-/cikit/issues/149
=> #149: Fix Nginx "24: Too many open files" while opening the main URL of a Matrix over HTTPS

scripts/provision.yml, scripts/roles/cikit-solr/vars/main.yml, tests/travis/bash/cikit.sh, tests/travis/bash/provision.sh
https://github.com/BR0kEN-/cikit/issues/151
=> #151: Replace Solr 6.6.3 and 7.3.0 by 6.6.4 and 7.4.0 accordingly

lib/getsitepackages.py, lib/variables.py
https://github.com/BR0kEN-/cikit/issues/153
=> #153: Use "distutils.sysconfig.get_python_lib()" when "site.getsitepackages()" is unavailable

scripts/provision.yml, scripts/roles/cikit-solr/vars/main.yml, tests/travis/bash/cikit.sh, tests/travis/bash/provision.sh
https://github.com/BR0kEN-/cikit/issues/155
=> #155: Replace Solr 6.6.4 by 6.6.5

cmf/drupal/all/scripts/tasks/reinstall/modes/full.yml
https://github.com/BR0kEN-/cikit/issues/157
=> #157: Allow templating "services.yml" for Drupal 8

docs/_data/navigation.yml, docs/_documentation/project/psql/README.md, scripts/provision.yml, scripts/roles/cikit-php/tasks/main.yml, scripts/roles/cikit-php/tasks/postgre.yml, scripts/roles/cikit-psql/tasks/main.yml, scripts/roles/cikit-psql/vars/main.yml
=> #159: Allow optional installation of the PostgreSQL
